<template>
  <view class="page"><jk-page-nav title="经营收益"/><view class="content">
    <view class="hero"><text>累计经营毛利（元）</text><strong>{{money(total)}}</strong><small>线下已实现，不属于平台待支付佣金</small></view>
    <view class="notice">例如区县代理调拨价差、本人线下销售毛利。该金额已在线下收款中实现，不进入平台提现账户，退货或调拨退回后会形成冲正。</view>
    <view v-for="x in list" :key="x.id" class="card"><view class="head"><strong>{{sourceLabel(x.sourceType)}}</strong><text>{{x.status}}</text></view><view class="source">{{x.sourceNo||x.profitNo}}</view><view class="calc"><text>收入 ¥{{money(x.revenueAmount)}}</text><text>成本 ¥{{money(x.costAmount)}}</text><strong>毛利 ¥{{money(x.profitAmount)}}</strong></view><view v-if="Number(x.reversedAmount||0)>0" class="reverse">已冲正 ¥{{money(x.reversedAmount)}}</view></view>
    <jk-empty v-if="loaded&&!list.length" text="暂无经营收益记录"/>
  </view></view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import JkEmpty from '@/components/jk/jk-empty.vue';import{getJkOperationProfitSummary,getJkOperationProfitList}from'@/api/jkV31.js';
export default{components:{JkPageNav,JkEmpty},data(){return{total:0,list:[],loaded:false}},created(){this.load()},onShow(){this.load()},methods:{load(){this.loaded=false;Promise.all([getJkOperationProfitSummary().catch(()=>0),getJkOperationProfitList({page:1,limit:100}).catch(()=>[])]) .then(([a,b])=>{this.total=a.data!==undefined?a.data:a;const d=b.data||b||[];this.list=Array.isArray(d)?d:(d.list||d.records||[])}).finally(()=>this.loaded=true)},money(v){const n=Number(v||0);return Number.isNaN(n)?String(v||0):n.toFixed(2)},sourceLabel(v){return{OFFLINE_SALE:'线下终端销售',STOCK_TRANSFER:'库存调拨价差',OFFLINE_SALE_RETURN:'线下销售退货冲正',STOCK_TRANSFER_RETURN:'调拨退回冲正'}[v]||v}}};
</script>
<style scoped>.page{min-height:100vh;background:#f7f9f9}.content{padding:16rpx 22rpx 38rpx}.hero{display:flex;flex-direction:column;align-items:center;padding:30rpx;border-radius:20rpx;background:linear-gradient(135deg,#eefbf8,#fff);border:1rpx solid #caeee4}.hero text{color:#708087;font-size:21rpx}.hero strong{margin-top:10rpx;color:#10a981;font-size:44rpx}.hero small{margin-top:7rpx;color:#8c989d;font-size:18rpx}.notice{margin:16rpx 0;padding:16rpx;border-radius:14rpx;background:#fff8e8;color:#8b6a22;font-size:19rpx;line-height:1.6}.card{margin-bottom:14rpx;padding:20rpx;border-radius:17rpx;background:#fff}.head{display:flex;justify-content:space-between}.head strong{font-size:24rpx}.head text{color:#7b888e;font-size:19rpx}.source{margin-top:8rpx;color:#89959a;font-size:18rpx}.calc{display:flex;align-items:center;justify-content:space-between;margin-top:15rpx;padding-top:13rpx;border-top:1rpx solid #edf1f0;color:#69767c;font-size:19rpx}.calc strong{color:#e6a23c;font-size:23rpx}.reverse{margin-top:9rpx;text-align:right;color:#df5f50;font-size:18rpx}</style>
