<template>
  <view class="commission-page"><jk-page-nav title="佣金明细"/><view class="tabs"><text v-for="item in filters" :key="item.value" :class="{active:active===item.value}" @tap="active=item.value">{{item.label}}</text></view><view class="summary"><view><text>可提现佣金（元）</text><strong>{{money(available)}}</strong></view><view><text>待结算佣金（元）</text><strong>{{money(pending)}}</strong></view><view><text>本月已结算（元）</text><strong>{{money(monthSettled)}}</strong></view></view><view class="list"><view v-for="item in commissionRows" :key="item.key" class="row" @tap="go(item.id)"><jk-icon :name="item.icon" size="lg"/><view class="main"><text>{{item.title}}</text><small>{{item.orderText}}</small><small>{{item.timeText}}</small></view><view class="right"><strong :class="{negative:item.negative}">{{item.amountText}}</strong><jk-status-tag :text="item.statusText" :tone="item.statusTone"/></view><text class="arrow">›</text></view><jk-empty v-if="loaded&&!filteredList.length" text="暂无佣金记录"/><view v-if="filteredList.length" class="no-more">没有更多了</view></view></view>
</template>
<script>
import JkPageNav from'@/components/jk/jk-page-nav.vue';import JkIcon from'@/components/jk/jk-icon.vue';import JkStatusTag from'@/components/jk/jk-status-tag.vue';import JkEmpty from'@/components/jk/jk-empty.vue';import{getJkCommissionList,getJkCommissionSummary}from'@/api/jk.js';import{jkCommissionStatusText,jkSourceTypeText}from'@/utils/jk-display.js';
export default{components:{JkPageNav,JkIcon,JkStatusTag,JkEmpty},data(){return{list:[],summary:{},active:'',loaded:false,filters:[{label:'全部',value:''},{label:'待结算',value:'PENDING'},{label:'已结算',value:'SETTLED'},{label:'已冲正',value:'REVERSED'}]}},computed:{filteredList(){return this.active?this.list.filter(x=>String(x.status||'').toUpperCase().includes(this.active)):this.list},commissionRows(){return this.filteredList.map((item,index)=>{const amount=Number(item.commissionAmount||0);return{key:item.id||index,id:item.id,icon:this.icon(item,index),title:item.sourceTypeText||this.sourceTypeText(item.sourceType)||'业务佣金',orderText:'订单号：'+(item.sourceNo||item.orderNo||'-'),timeText:this.formatTime(item.createTime),negative:amount<0,amountText:this.signed(amount),statusText:item.commissionStatusText||item.statusText||this.commissionStatusText(item.status),statusTone:this.tone(item.status)}})},available(){const f=this.summary.fundAccount||{};return f.availableAmount||this.summary.withdrawableAmount||0},pending(){const c=this.summary.commissionAccount||{};return c.pendingSettleAmount||c.pendingAmount||this.summary.pendingSettleAmount||0},monthSettled(){return this.summary.monthSettledAmount||this.summary.currentMonthSettled||0}},onShow(){this.load()},methods:{load(){getJkCommissionList({page:1,limit:100}).then(r=>{const d=r.data||r||[];this.list=Array.isArray(d)?d:(d.list||d.records||[])}).catch(()=>this.list=[]).finally(()=>this.loaded=true);getJkCommissionSummary().then(r=>this.summary=r.data||r||{}).catch(()=>{})},money(v){const n=Number(v||0);return Number.isNaN(n)?String(v||'0.00'):n.toFixed(2)},signed(v){const n=Number(v||0);return(n>=0?'+':'')+this.money(n)},formatTime(v){return v?String(v).replace('T',' ').slice(0,19):'-'},commissionStatusText(v){return jkCommissionStatusText(v)},sourceTypeText(v){return jkSourceTypeText(v)},tone(s){const t=String(s||'').toUpperCase();if(t.includes('REVERSE'))return'danger';if(t.includes('SETTLE'))return'success';return'info'},icon(item,i){const t=String(item.sourceType||'').toUpperCase();if(t.includes('TEAM'))return'team';if(t.includes('REFUND'))return'error';return i%3===0?'wallet':i%3===1?'document':'money'},go(id){if(id)uni.navigateTo({url:'/pages/jk/commission/detail?id='+id})}}};
</script>
<style scoped>
.commission-page{min-height:100vh;background:#fff}.tabs{display:flex;border-bottom:1rpx solid #edf1f0}.tabs text{position:relative;flex:1;padding:20rpx 0;color:#707c82;text-align:center;font-size:23rpx}.tabs text.active{color:#10b981;font-weight:700}.tabs text.active::after{position:absolute;right:34%;bottom:0;left:34%;height:4rpx;background:#10b981;content:''}.summary{display:flex;margin:16rpx 22rpx 0;padding:20rpx 8rpx;border-radius:17rpx;background:linear-gradient(135deg,#effbf8,#fff)}.summary>view{display:flex;flex:1;flex-direction:column;align-items:center;border-right:1rpx solid #e0ece9}.summary>view:last-child{border-right:0}.summary text{color:#7a878d;font-size:18rpx}.summary strong{margin-top:8rpx;color:#263139;font-size:26rpx}.list{padding:0 22rpx}.row{display:flex;align-items:center;min-height:126rpx;border-bottom:1rpx solid #edf1f0}.main{display:flex;min-width:0;flex:1;flex-direction:column;gap:5rpx;margin-left:10rpx}.main text{color:#28343a;font-size:23rpx;font-weight:600}.main small{color:#8b969c;font-size:18rpx}.right{display:flex;flex-direction:column;align-items:flex-end;gap:7rpx}.right strong{color:#10b981;font-size:25rpx}.right strong.negative{color:#ef5b4c}.arrow{margin-left:7rpx;color:#9ca6ab;font-size:32rpx}.no-more{padding:26rpx;color:#9ba5aa;text-align:center;font-size:19rpx}
</style>
