<template>
  <view class="complete-page"><jk-page-nav :title="mode==='order'?'订货完成':'调拨完成'" transparent/><view class="complete-content"><image class="complete-visual" src="/static/jk-ui-v2/illustrations/business-hero.png" mode="aspectFit"/><view class="complete-title"><image src="/static/jk-ui-v2/icons/success.png"/><text>{{ mode==='order'?'订货已完成':'调拨已完成' }}</text></view><text class="complete-desc">商品已成功{{ mode==='order'?'入库':'调拨' }}，请及时跟踪库存与业务情况。</text><view v-if="detail" class="info-card"><view class="row"><jk-icon name="document" size="sm"/><text>{{ mode==='order'?'订单号':'调拨单号' }}</text><strong>{{ no }}</strong></view><view class="row"><jk-icon name="clock" size="sm"/><text>完成时间</text><strong>{{ formatTime(detail.stockInTime||detail.receiveTime||detail.updateTime) }}</strong></view><view class="row"><jk-icon name="user" size="sm"/><text>接收方</text><strong>{{ detail.receiverName||detail.applicantName||'-' }}</strong></view><view class="row"><jk-icon name="stock" size="sm"/><text>商品数</text><strong>{{ items.length }} 种商品</strong></view><view class="row"><jk-icon name="location" size="sm"/><text>所属区域</text><strong>{{ detail.regionName||'-' }}</strong></view></view><view v-if="items.length" class="product-card"><view class="section-head"><text>商品清单</text><small>共 {{items.length}} 种商品</small></view><jk-product-row v-for="(item,index) in items" :key="item.id||index" :item="item" :fallback="fallback(index)"><view slot="right" class="qty"><small>数量</small><strong>{{item.quantity||0}} {{item.unitName||''}}</strong></view></jk-product-row></view></view><view class="bottom-actions"><button class="primary-btn" @tap="viewDetail">查看详情</button><button class="outline-btn" @tap="backBusiness">返回业务中心</button></view></view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import JkIcon from '@/components/jk/jk-icon.vue';import JkProductRow from '@/components/jk/jk-product-row.vue';import{getJkPlatformOrderDetail,getJkStockTransferDetail}from'@/api/jk.js';
export default{components:{JkPageNav,JkIcon,JkProductRow},data(){return{mode:'transfer',id:0,detail:null,items:[]}},computed:{no(){return this.mode==='order'?this.detail.platformOrderNo:this.detail.transferNo}},onLoad(q){this.mode=q.mode==='order'?'order':'transfer';this.id=Number(q.id);this.load()},methods:{load(){(this.mode==='order'?getJkPlatformOrderDetail:getJkStockTransferDetail)(this.id).then(r=>{const p=r.data||r||{};this.detail=this.mode==='order'?(p.order||p):(p.transfer||p);this.items=p.items||[]})},formatTime(v){return v?String(v).replace('T',' ').slice(0,19):'-'},fallback(i){return['/static/jk-ui-v2/products/glucose-paper.png','/static/jk-ui-v2/products/meter.png'][i%2]},viewDetail(){uni.redirectTo({url:'/pages/jk/trade/detail?mode='+this.mode+'&id='+this.id})},backBusiness(){uni.redirectTo({url:'/pages/jk/business/index'})}}};
</script>
<style scoped>
.complete-page{min-height:100vh;padding-bottom:190rpx;background:radial-gradient(circle at 50% 21%,#e6fff8 0,#f9fffd 32%,#fff 58%)}.complete-content{padding:10rpx 22rpx 34rpx;text-align:center}.complete-visual{width:300rpx;height:230rpx}.complete-title{display:flex;align-items:center;justify-content:center;gap:12rpx;margin-top:-10rpx}.complete-title image{width:48rpx;height:48rpx}.complete-title text{color:#1d272d;font-size:36rpx;font-weight:800}.complete-desc{display:block;margin-top:12rpx;color:#77838a;font-size:23rpx}.info-card,.product-card{margin-top:26rpx;padding:0 22rpx;border-radius:20rpx;background:#fff;box-shadow:0 8rpx 24rpx rgba(24,68,58,.05);text-align:left}.row{display:grid;grid-template-columns:46rpx 170rpx 1fr;align-items:center;min-height:76rpx;border-bottom:1rpx solid #edf1f0}.row:last-child{border-bottom:0}.row>text{color:#748087;font-size:23rpx}.row strong{color:#273239;text-align:right;font-size:23rpx;font-weight:500}.section-head{display:flex;align-items:center;justify-content:space-between;padding:22rpx 0 8rpx}.section-head text{color:#1f2937;font-size:28rpx;font-weight:700}.section-head small{color:#8b969c;font-size:20rpx}.qty{display:flex;flex-direction:column;align-items:flex-end;gap:6rpx}.qty small{color:#8b969c;font-size:19rpx}.qty strong{color:#10b981;font-size:24rpx}.bottom-actions{position:fixed;z-index:40;right:0;bottom:0;left:0;padding:14rpx 22rpx calc(18rpx + env(safe-area-inset-bottom));background:rgba(255,255,255,.98)}.bottom-actions button{height:76rpx;margin:0 0 12rpx;border-radius:38rpx;font-size:26rpx;line-height:76rpx}.bottom-actions button::after{border:0}.primary-btn{background:#10b981!important;color:#fff!important}.outline-btn{border:2rpx solid #10b981!important;background:#fff!important;color:#10a981!important}
</style>
