<template>
  <view class="receive-page"><jk-page-nav title="收货确认"/><view v-if="detail" class="receive-content"><view class="summary-card"><jk-icon name="document" size="lg"/><view><text>{{ mode==='order'?'订单号':'调拨单号' }}</text><strong>{{ no }}</strong></view><jk-status-tag :text="detail.statusText||'待收货'" tone="success"/></view><view class="section-title">商品确认</view><view class="table-head"><text>商品信息</text><text>订购数量</text><text>实收数量</text></view><view v-for="(item,index) in items" :key="item.id||index" class="receive-row"><image :src="item.productImage||fallback(index)" mode="aspectFill"/><view class="product-main"><text>{{ item.productName||'商品已删除' }}</text><small>{{ item.skuText||item.skuName||'默认规格' }}</small></view><text>{{ item.quantity||0 }}</text><strong>{{ item.quantity||0 }}</strong></view><view class="tip"><image src="/static/jk-ui-v2/icons/info.png"/><text>确认收货后，平台将完成订单入库处理。</text></view></view><jk-bottom-action><button class="primary-btn" :disabled="submitting" @tap="confirm">{{ submitting?'处理中...':'确认收货' }}</button></jk-bottom-action></view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import JkIcon from '@/components/jk/jk-icon.vue';import JkStatusTag from '@/components/jk/jk-status-tag.vue';import JkBottomAction from '@/components/jk/jk-bottom-action.vue';import{getJkPlatformOrderDetail,getJkStockTransferDetail,receiveJkPlatformOrder,receiveJkStockTransfer}from'@/api/jk.js';
export default{components:{JkPageNav,JkIcon,JkStatusTag,JkBottomAction},data(){return{mode:'order',id:0,detail:null,items:[],submitting:false}},computed:{no(){return this.mode==='order'?this.detail.platformOrderNo:this.detail.transferNo}},onLoad(q){this.mode=q.mode==='transfer'?'transfer':'order';this.id=Number(q.id);this.load()},methods:{load(){(this.mode==='order'?getJkPlatformOrderDetail:getJkStockTransferDetail)(this.id).then(r=>{const p=r.data||r||{};this.detail=this.mode==='order'?(p.order||p):(p.transfer||p);this.items=p.items||[]})},fallback(i){return['/static/jk-ui-v2/products/meter.png','/static/jk-ui-v2/products/glucose-paper.png'][i%2]},confirm(){uni.showModal({title:'确认收货',content:'确认后将进行库存入库，请核对实际收货数量。',success:r=>{if(!r.confirm)return;this.submitting=true;(this.mode==='order'?receiveJkPlatformOrder:receiveJkStockTransfer)(this.id,{remark:'APP确认收货'}).then(()=>uni.redirectTo({url:'/pages/jk/trade/complete?mode='+this.mode+'&id='+this.id})).finally(()=>this.submitting=false)}})}}};
</script>
<style scoped>
.receive-page{min-height:100vh;padding-bottom:126rpx;background:#fff}.receive-content{padding:18rpx 22rpx 36rpx}.summary-card{display:flex;align-items:center;padding:20rpx;border-radius:18rpx;background:linear-gradient(135deg,#eafbf7,#f8fffd)}.summary-card>view:nth-child(2){display:flex;flex:1;flex-direction:column;margin-left:12rpx}.summary-card text{color:#76838a;font-size:21rpx}.summary-card strong{margin-top:5rpx;color:#263139;font-size:24rpx}.section-title{margin-top:26rpx;color:#1f2937;font-size:28rpx;font-weight:700}.table-head{display:grid;grid-template-columns:1fr 120rpx 120rpx;margin-top:18rpx;padding:14rpx;background:#f8faf9;color:#7b878d;font-size:20rpx}.table-head text:nth-child(n+2){text-align:center}.receive-row{display:grid;grid-template-columns:90rpx 1fr 120rpx 120rpx;align-items:center;min-height:116rpx;border-bottom:1rpx solid #edf1f0}.receive-row image{width:76rpx;height:76rpx;border-radius:10rpx}.product-main{display:flex;min-width:0;flex-direction:column;gap:6rpx}.product-main text{overflow:hidden;color:#273239;font-size:23rpx;font-weight:600;text-overflow:ellipsis;white-space:nowrap}.product-main small{color:#8b969c;font-size:19rpx}.receive-row>text,.receive-row>strong{text-align:center;font-size:22rpx}.receive-row>strong{color:#10b981}.tip{display:flex;align-items:center;gap:8rpx;margin-top:18rpx;padding:15rpx;border-radius:12rpx;background:#eafaf6;color:#708b83;font-size:21rpx}.tip image{width:30rpx;height:30rpx}.primary-btn{border:0!important;background:#10b981!important;color:#fff!important}
</style>
