<template>
  <view class="mall-page"><headerSearch :isScrolled="false" :dataConfig="homeSearchConfig"></headerSearch><view class="mall-content">
    <view class="mall-tabs"><text v-for="item in tabs" :key="item.key" :class="{active: activeTab===item.key}" @click="switchTab(item.key)">{{ item.label }}</text></view>
    <image class="mall-banner" src="http://jzk.wit.cn/crmebimage/public/product/2026/07/13/mall-banner-glucose-management.png" mode="aspectFill" />
    <view class="mall-filters"><text v-for="item in filters" :key="item.key" :class="{active: sortKey===item.key}" @click="sort(item.key)">{{ item.label }} {{ sortKey===item.key && sortDirection ? (sortDirection==='asc'?'↑':'↓') : '' }}</text></view>
    <view class="mall-grid"><view class="mall-card" v-for="item in products" :key="item.id" @click="detail(item)"><image :src="item.image" mode="aspectFill"/><view class="mall-card__content"><view class="mall-card__title-row"><text class="mall-card__name">{{ item.storeName }}</text></view><view class="mall-card__tags"><text v-if="item.brandName">{{ item.brandName }}</text><text v-if="item.unitName">{{ item.unitName }}</text></view><view class="mall-card__bottom"><view><text class="mall-card__price">¥{{ item.price }}</text><text class="mall-card__sales">月销 {{ Number(item.sales || 0) }}</text></view><button @click.stop="buy(item)">下单</button></view></view></view></view>
    <view v-if="loading" class="mall-empty">正在加载商品…</view><view v-else-if="!products.length" class="mall-empty">暂无商品</view>
  </view><pageFooter></pageFooter></view>
</template>
<script>
import { getProductslist } from '@/api/store.js';
import { goShopDetail } from '@/libs/order.js';
import { mapGetters } from 'vuex';
import headerSearch from '@/components/homeIndex/headerSearch';
import pageFooter from '@/components/pageFooter/index.vue';
export default { components:{headerSearch,pageFooter}, computed: mapGetters(['uid']), data(){ return { homeSearchConfig:{titleConfig:{val:3},logoConfig:{url:''},logoFixConfig:{url:''},searConfig:{tabVal:0},bgStyle:{val:20},bgColor:{color:[{item:'#32c7b1'},{item:'#61d2c2'}]},lrConfig:{val:12},contentStyle:{val:20},borderColor:{color:[{item:'#ffffff'}]},textColor:{color:[{item:'#9aa5a4'}]},textPosition:{tabVal:0,list:[{style:'left'}]},hotWords:{list:[]},placeWords:{val:'搜索商品'}}, products:[], loading:false, activeTab:'recommend', sortKey:'recommend', sortDirection:'', where:{keyword:'',priceOrder:'',salesOrder:'',ratingOrder:'',news:0,page:1,limit:20,cid:''}, tabs:[{key:'recommend',label:'推荐'},{key:'hot',label:'热销'},{key:'new',label:'新品'},{key:'package',label:'套餐'}], filters:[{key:'sales',label:'销量'},{key:'price',label:'价格'},{key:'recommend',label:'推荐'},{key:'rating',label:'评价'}] }; }, onLoad(options){ this.where.cid=options.cid || ''; this.fetch(); }, methods:{ request(){ return { ...this.where }; }, fetch(){ this.loading=true; getProductslist(this.request()).then(res=>{ this.products=(res.data && res.data.list) || []; }).finally(()=>{ this.loading=false; }); }, reset(){ this.where.priceOrder=''; this.where.salesOrder=''; this.where.ratingOrder=''; this.where.news=0; }, switchTab(key){ this.activeTab=key; this.sortKey='recommend'; this.sortDirection=''; this.reset(); if(key==='hot') this.where.salesOrder='desc'; if(key==='new') this.where.news=1; this.fetch(); }, sort(key){ const next=this.sortKey===key && this.sortDirection==='asc'?'desc':'asc'; this.sortKey=key; this.sortDirection=key==='recommend'?'':next; this.reset(); if(key==='sales') this.where.salesOrder=next; if(key==='price') this.where.priceOrder=next; if(key==='rating') this.where.ratingOrder=next; this.fetch(); }, search(){ this.where.page=1; this.fetch(); }, detail(item){ goShopDetail(item,this.uid).then(()=>uni.navigateTo({url:'/pages/goods/goods_details/index?id='+item.id})); }, buy(item){ this.detail(item); } } };
</script>
<style lang="scss" scoped>
.mall-page{min-height:100vh;background:#f7f8fa}.mall-content{padding:0 22rpx 140rpx}.mall-head{padding:10rpx 0 18rpx}.mall-search{display:flex;align-items:center;height:76rpx;padding:0 26rpx;border-radius:999rpx;background:#fff;color:#aab1b3}.mall-search input{flex:1;margin-left:16rpx;font-size:27rpx}.mall-tabs,.mall-filters{display:flex;justify-content:space-between;align-items:center}.mall-tabs{padding:8rpx 10rpx 18rpx;color:#fff;font-size:30rpx}.mall-tabs text{padding-bottom:10rpx}.mall-tabs .active{border-bottom:5rpx solid #fff;font-weight:700}.mall-banner{width:100%;height:312rpx;border-radius:18rpx;background:#dff4ed}.mall-filters{margin:18rpx 0;padding:18rpx 20rpx;border-radius:10rpx;background:#fff;color:#747b80;font-size:26rpx}.mall-filters .active{color:#18b997;font-weight:600}.mall-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18rpx}.mall-card{overflow:hidden;border-radius:16rpx;background:#fff}.mall-card>image{width:100%;height:230rpx;background:#f1f4f3}.mall-card__content{padding:16rpx 16rpx 18rpx}.mall-card__title-row{display:flex;align-items:flex-start;min-height:72rpx}.mall-card__name{display:-webkit-box;overflow:hidden;word-break:break-all;-webkit-box-orient:vertical;-webkit-line-clamp:2;color:#31363a;font-size:27rpx;font-weight:600;line-height:36rpx}.mall-card__tags{display:flex;align-items:center;gap:8rpx;min-height:38rpx;padding:8rpx 0 6rpx;overflow:hidden;white-space:nowrap}.mall-card__tags text{flex:none;padding:2rpx 7rpx;border:1rpx solid #63d8c1;border-radius:8rpx;color:#27b99c;font-size:18rpx}.mall-card__bottom{display:flex;align-items:flex-end;justify-content:space-between;padding-top:4rpx}.mall-card__price{display:block;color:#ef4c52;font-size:40rpx;font-weight:700}.mall-card__sales{display:block;color:#a6abae;font-size:18rpx}.mall-card button{min-width:76rpx;height:48rpx;margin:0;border-radius:999rpx;background:#1fc5a2;color:#fff;font-size:23rpx;line-height:48rpx}.mall-empty{padding:70rpx 0;text-align:center;color:#a7adb0;font-size:26rpx}

/* Use one home search bar only, with tabs in the same top visual block. */
.mall-page /deep/ .mp-header,.mall-page /deep/ .sys-head{background:#32c7b1!important}.mall-tabs{margin:0 -22rpx;padding:10rpx 32rpx 20rpx;background:linear-gradient(135deg,#32c7b1,#61d2c2);color:#eafffb}.mall-tabs .active{color:#075d54;border-bottom-color:#075d54}.mall-banner{margin-top:16rpx}
</style>

