<template>
  <view class="page"><jk-page-nav title="盘点详情"/><view v-if="detail" class="content">
    <view class="hero"><view><text>{{statusText(detail.status)}}</text><small>{{detail.checkNo}}</small></view><strong>差异 {{detail.differenceQuantity||0}}</strong></view>
    <view class="notice" v-if="detail.status==='COUNTING'">请逐项核对实盘数量。每次保存都会更新当前盘点草稿，全部确认后再提交审核。</view>
    <view v-for="x in detail.items||[]" :key="x.id" class="item"><view class="info"><strong>{{x.productName||('商品'+x.productId)}}</strong><small>{{x.skuName||x.skuCode||x.skuId}}</small><text>账面库存 {{x.bookQuantity||0}}</text></view><view class="count"><text>实盘</text><input v-model.number="x.actualQuantity" type="number" :disabled="detail.status!=='COUNTING'"/><button v-if="detail.status==='COUNTING'" @tap="saveItem(x)">保存</button></view><view v-if="x.actualQuantity!=null" class="diff">差异 {{Number(x.actualQuantity)-Number(x.bookQuantity||0)}} · {{x.adjustStatus||'待调整'}}</view></view>
    <button v-if="detail.status==='COUNTING'" class="submit" @tap="submit">提交审核</button>
    <view class="tip">盘点审核通过后，盘盈和盘亏均通过统一库存流水调整，不直接修改库存字段。</view>
  </view></view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import{getJkStockCheckDetail,countJkStockCheck,submitJkStockCheck}from'@/api/jkV31.js';
export default{components:{JkPageNav},data(){return{id:0,detail:null}},onLoad(q){this.id=Number(q.id);this.load()},methods:{load(){getJkStockCheckDetail(this.id).then(r=>this.detail=r.data||r||null)},saveItem(x){if(x.actualQuantity==null||Number(x.actualQuantity)<0)return this.$util.Tips({title:'实盘数量不能小于0'});countJkStockCheck(this.id,{itemId:x.id,actualQuantity:Number(x.actualQuantity),remark:'小程序实盘录入'}).then(()=>{this.$util.Tips({title:'已保存'});this.load()})},submit(){const items=this.detail.items||[];if(items.some(x=>x.actualQuantity==null))return this.$util.Tips({title:'请先录入全部商品实盘数量'});uni.showModal({title:'提交盘点审核',content:'提交后不能继续修改实盘数量，确认提交？',success:r=>{if(r.confirm)submitJkStockCheck(this.id,{requestNo:'SUBMIT-'+this.id+'-'+Date.now(),remark:'小程序提交盘点审核'}).then(()=>{this.$util.Tips({title:'已提交审核'});this.load()})}})},statusText(v){return{COUNTING:'盘点中',SUBMITTED:'待审核',APPROVED:'已通过',REJECTED:'已驳回',CANCELLED:'已取消'}[v]||v}}};
</script>
<style scoped>.page{min-height:100vh;background:#f7f9f9}.content{padding:16rpx 22rpx 42rpx}.hero{display:flex;align-items:center;justify-content:space-between;padding:26rpx 22rpx;border-radius:20rpx;background:linear-gradient(135deg,#15b98f,#52d2b3);color:#fff}.hero>view{display:flex;flex-direction:column;gap:7rpx}.hero text{font-size:30rpx;font-weight:700}.hero small{font-size:19rpx;opacity:.9}.hero strong{font-size:25rpx}.notice,.tip{margin-top:16rpx;padding:16rpx;border-radius:14rpx;background:#fff8e8;color:#89681f;font-size:19rpx;line-height:1.6}.item{margin-top:15rpx;padding:20rpx;border-radius:18rpx;background:#fff}.info{display:flex;flex-direction:column;gap:6rpx}.info strong{font-size:24rpx}.info small,.info text{color:#859197;font-size:19rpx}.count{display:flex;align-items:center;margin-top:15rpx;padding-top:14rpx;border-top:1rpx solid #edf1f0}.count text{color:#66737a;font-size:21rpx}.count input{width:140rpx;height:56rpx;margin-left:auto;padding:0 12rpx;border-radius:10rpx;background:#f4f7f6;text-align:center;font-size:23rpx}.count button{height:56rpx;margin:0 0 0 10rpx;padding:0 20rpx;border-radius:28rpx;background:#10b981;color:#fff;font-size:20rpx;line-height:56rpx}.diff{margin-top:10rpx;color:#e6a23c;font-size:19rpx}.submit{height:82rpx;margin-top:20rpx;border-radius:41rpx;background:#10b981;color:#fff;font-size:26rpx;line-height:82rpx}</style>