<template>
  <view class="page"><jk-page-nav title="库存盘点"/><view class="content">
    <view class="notice">盘点会先固化当前账面库存。提交后如库存已因订货、调拨或销售发生变化，后台会拒绝使用过期盘点覆盖真实库存。</view>
    <button class="create" :disabled="creating||!stockAccountId" @tap="createCheck">＋ 创建盘点快照</button>
    <scroll-view scroll-x class="tabs"><text v-for="x in tabs" :key="x.value" :class="{active:status===x.value}" @tap="change(x.value)">{{x.label}}</text></scroll-view>
    <view v-for="x in list" :key="x.id" class="card" @tap="open(x)"><view class="head"><strong>{{x.checkNo}}</strong><jk-status-tag :text="statusText(x.status)" :tone="tone(x.status)"/></view><view class="meta"><text>快照 {{time(x.snapshotTime)}}</text><text>差异 {{x.differenceQuantity||0}}</text></view><view class="amount">差异金额 <strong>¥{{money(x.differenceAmount)}}</strong></view></view>
    <jk-empty v-if="loaded&&!list.length" text="暂无盘点记录"/>
  </view></view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import JkStatusTag from '@/components/jk/jk-status-tag.vue';import JkEmpty from '@/components/jk/jk-empty.vue';
import{getJkMyStock}from'@/api/jk.js';import{getJkStockCheckList,createJkStockCheck}from'@/api/jkV31.js';
export default{components:{JkPageNav,JkStatusTag,JkEmpty},data(){return{stock:{},list:[],status:'',loaded:false,creating:false,tabs:[{label:'全部',value:''},{label:'盘点中',value:'COUNTING'},{label:'待审核',value:'SUBMITTED'},{label:'已完成',value:'APPROVED'}]}},computed:{stockAccountId(){const items=this.stock.items||this.stock.records||[];return this.stock.stockAccountId||this.stock.accountId||(items[0]&&items[0].stockAccountId)||null}},onShow(){this.load()},methods:{load(){this.loaded=false;Promise.all([getJkMyStock().catch(()=>({})),getJkStockCheckList({page:1,limit:100,status:this.status||undefined}).catch(()=>[])]) .then(([a,b])=>{this.stock=a.data||a||{};const d=b.data||b||[];this.list=Array.isArray(d)?d:(d.list||d.records||[])}).finally(()=>this.loaded=true)},change(v){this.status=v;this.load()},createCheck(){if(!this.stockAccountId)return this.$util.Tips({title:'未找到当前身份的库存账户'});this.creating=true;createJkStockCheck({requestNo:'CHECK-'+Date.now(),stockAccountId:this.stockAccountId,checkType:'FULL',remark:'小程序发起全盘'}).then(r=>{const d=r.data||r||{};uni.navigateTo({url:'/pages/jk/stock/checkDetail?id='+d.id})}).finally(()=>this.creating=false)},open(x){uni.navigateTo({url:'/pages/jk/stock/checkDetail?id='+x.id})},statusText(v){return{COUNTING:'盘点中',SUBMITTED:'待审核',APPROVED:'已通过',REJECTED:'已驳回',CANCELLED:'已取消'}[v]||v},tone(v){return v==='APPROVED'?'success':v==='REJECTED'?'danger':v==='SUBMITTED'?'warning':'info'},time(v){return v?String(v).replace('T',' ').slice(0,16):'--'},money(v){return Number(v||0).toFixed(2)}}};
</script>
<style scoped>.page{min-height:100vh;background:#f7f9f9}.content{padding:16rpx 22rpx 40rpx}.notice{padding:18rpx;border-radius:15rpx;background:#fff8e8;color:#8b6a22;font-size:20rpx;line-height:1.65}.create{height:76rpx;margin-top:16rpx;border-radius:38rpx;background:#10b981;color:#fff;font-size:24rpx;line-height:76rpx}.create[disabled]{opacity:.5}.tabs{margin:18rpx 0;white-space:nowrap}.tabs text{display:inline-block;margin-right:10rpx;padding:11rpx 20rpx;border-radius:25rpx;background:#fff;color:#748187;font-size:20rpx}.tabs text.active{background:#10b981;color:#fff}.card{margin-bottom:14rpx;padding:20rpx;border-radius:18rpx;background:#fff}.head,.meta,.amount{display:flex;align-items:center;justify-content:space-between}.head strong{font-size:24rpx}.meta{margin-top:13rpx;color:#879299;font-size:19rpx}.amount{margin-top:14rpx;padding-top:12rpx;border-top:1rpx solid #edf1f0;color:#69767c;font-size:20rpx}.amount strong{color:#e6a23c;font-size:25rpx}</style>