<template>
  <view class="withdraw-list-page"><jk-page-nav title="提现记录"/><view class="tabs"><text v-for="item in filters" :key="item.value" :class="{active:active===item.value}" @tap="active=item.value">{{item.label}}</text></view><view class="summary"><jk-icon name="wallet" size="md"/><view><text>累计提现金额（元）</text><strong>{{money(totalWithdraw)}}</strong></view><view><text>成功到账金额（元）</text><strong>{{money(successAmount)}}</strong></view><view><text>提现笔数（笔）</text><strong>{{list.length}}</strong></view></view><view class="list"><view v-for="(item,index) in filteredList" :key="item.id||index" class="row" @tap="go(item.id)"><jk-icon :name="icon(item)" size="lg"/><view class="main"><text>¥{{money(item.amount)}}</text><small>申请时间：{{formatTime(item.createTime)}}</small><small>到账银行卡：{{accountText(item)}}</small><view v-if="item.rejectReason" class="reject-reason">拒绝原因：{{item.rejectReason}}</view></view><jk-status-tag :text="item.withdrawStatusText||item.statusText||withdrawStatusText(item.status)" :tone="tone(item.status)"/><text class="arrow">›</text></view><jk-empty v-if="loaded&&!filteredList.length" text="暂无提现记录"/><view v-if="filteredList.length" class="no-more">没有更多了</view></view></view>
</template>
<script>
import JkPageNav from'@/components/jk/jk-page-nav.vue';import JkIcon from'@/components/jk/jk-icon.vue';import JkStatusTag from'@/components/jk/jk-status-tag.vue';import JkEmpty from'@/components/jk/jk-empty.vue';import{getJkWithdrawList}from'@/api/jk.js';import{jkWithdrawStatusText}from'@/utils/jk-display.js';
export default{components:{JkPageNav,JkIcon,JkStatusTag,JkEmpty},data(){return{list:[],active:'',loaded:false,filters:[{label:'全部',value:''},{label:'处理中',value:'PROCESSING'},{label:'已到账',value:'PAID'},{label:'已拒绝',value:'REJECTED'}]}},computed:{filteredList(){return this.active?this.list.filter(x=>this.normalizeStatus(x.status)===this.active):this.list},totalWithdraw(){return this.list.reduce((s,x)=>s+Number(x.amount||0),0)},successAmount(){return this.list.filter(x=>this.normalizeStatus(x.status)==='PAID').reduce((s,x)=>s+Number(x.amount||0),0)}},onShow(){getJkWithdrawList({page:1,limit:100}).then(r=>{const d=r.data||r||[];this.list=Array.isArray(d)?d:(d.list||d.records||[])}).catch(()=>this.list=[]).finally(()=>this.loaded=true)},methods:{normalizeStatus(s){const t=String(s||'').toUpperCase();if(t.includes('REJECT'))return'REJECTED';if(t.includes('PAID')||t.includes('SUCCESS')||t.includes('CONFIRM'))return'PAID';return'PROCESSING'},money(v){const n=Number(v||0);return Number.isNaN(n)?String(v||'0.00'):n.toFixed(2)},formatTime(v){return v?String(v).replace('T',' ').slice(0,19):'-'},withdrawStatusText(v){return jkWithdrawStatusText(v)},tone(s){const n=this.normalizeStatus(s);return n==='PAID'?'success':n==='REJECTED'?'danger':'info'},icon(item){const n=this.normalizeStatus(item.status);return n==='PAID'?'wallet':n==='REJECTED'?'error':'clock'},accountText(item){try{const d=typeof item.payeeSnapshotJson==='string'?JSON.parse(item.payeeSnapshotJson):item.payeeSnapshotJson||{};return d.bankName||d.account||'收款账户'}catch(e){return'收款账户'}},go(id){if(id)uni.navigateTo({url:'/pages/jk/withdraw/detail?id='+id})}}};
</script>
<style scoped>
.withdraw-list-page{min-height:100vh;background:#fff}.tabs{display:flex;border-bottom:1rpx solid #edf1f0}.tabs text{position:relative;flex:1;padding:20rpx 0;color:#707c82;text-align:center;font-size:23rpx}.tabs text.active{color:#10b981;font-weight:700}.tabs text.active::after{position:absolute;right:35%;bottom:0;left:35%;height:4rpx;background:#10b981;content:''}.summary{display:grid;grid-template-columns:60rpx 1.2fr 1.2fr .8fr;align-items:center;margin:16rpx 22rpx 0;padding:18rpx;border-radius:17rpx;background:linear-gradient(135deg,#effbf8,#fff)}.summary>view:not(:first-child){display:flex;flex-direction:column;align-items:center;border-right:1rpx solid #e1ece9}.summary>view:last-child{border-right:0}.summary text{color:#7e8a90;font-size:16rpx}.summary strong{margin-top:6rpx;color:#263139;font-size:23rpx}.list{padding:0 22rpx}.row{display:flex;align-items:flex-start;min-height:132rpx;padding:18rpx 0;border-bottom:1rpx solid #edf1f0}.main{display:flex;min-width:0;flex:1;flex-direction:column;gap:5rpx;margin-left:10rpx}.main>text{color:#263139;font-size:27rpx;font-weight:700}.main small{color:#8b969c;font-size:18rpx}.reject-reason{margin-top:5rpx;padding:7rpx 9rpx;border-radius:7rpx;background:#fff1ef;color:#ef5b4c;font-size:17rpx}.row ::v-deep .jk-status-tag{margin-top:4rpx}.arrow{margin-left:6rpx;color:#9ba5aa;font-size:31rpx}.no-more{padding:24rpx;color:#9aa4a9;text-align:center;font-size:18rpx}
</style>
