<template>
  <view class="page"><jk-page-nav title="我的业绩"/><view class="content">
    <view class="summary"><view><text>累计有效业绩</text><strong>¥{{money(summary.total)}}</strong></view><view><text>线上零售</text><strong>{{money(summary.onlineRetail)}}</strong></view><view><text>线下零售</text><strong>{{money(summary.offlineRetail)}}</strong></view></view>
    <view class="notice">业绩用于经营统计和阶梯判断，不等于可提现佣金。内部订货或调拨可以形成业绩，但只有命中已发布奖励规则时才会产生佣金。</view>
    <scroll-view scroll-x class="tabs"><text v-for="x in types" :key="x.value" :class="{active:type===x.value}" @tap="change(x.value)">{{x.label}}</text></scroll-view>
    <view v-for="x in list" :key="x.id" class="card"><view class="head"><strong>{{label(x.performanceType)}}</strong><text>{{x.status}}</text></view><view class="no">{{x.sourceNo||x.performanceNo}}</view><view class="amount"><text>{{x.occurredAt}}</text><strong>¥{{money(Number(x.performanceAmount||0)-Number(x.reversedAmount||0))}}</strong></view><view v-if="Number(x.reversedAmount||0)>0" class="reverse">原业绩 ¥{{money(x.performanceAmount)}}，已冲正 ¥{{money(x.reversedAmount)}}</view></view>
    <jk-empty v-if="loaded&&!list.length" text="暂无业绩记录"/>
  </view></view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import JkEmpty from '@/components/jk/jk-empty.vue';import{getJkPerformanceSummary,getJkPerformanceList}from'@/api/jkV31.js';
export default{components:{JkPageNav,JkEmpty},data(){return{summary:{},list:[],type:'',loaded:false,types:[{label:'全部',value:''},{label:'线上零售',value:'RETAIL_ONLINE'},{label:'线下零售',value:'RETAIL_OFFLINE'},{label:'平台订货',value:'PLATFORM_PURCHASE'},{label:'库存调拨',value:'STOCK_TRANSFER'},{label:'库存周转',value:'INVENTORY_TURNOVER'}]}},onShow(){this.load()},methods:{load(){this.loaded=false;Promise.all([getJkPerformanceSummary().catch(()=>({})),getJkPerformanceList({page:1,limit:100,performanceType:this.type||undefined}).catch(()=>[])]) .then(([a,b])=>{this.summary=a.data||a||{};const d=b.data||b||[];this.list=Array.isArray(d)?d:(d.list||d.records||[])}).finally(()=>this.loaded=true)},change(v){this.type=v;this.load()},label(v){const x=this.types.find(i=>i.value===v);return x?x.label:v},money(v){const n=Number(v||0);return Number.isNaN(n)?String(v||0):n.toFixed(2)}}};
</script>
<style scoped>.page{min-height:100vh;background:#f7f9f9}.content{padding:16rpx 22rpx 38rpx}.summary{display:flex;padding:25rpx 8rpx;border-radius:20rpx;background:linear-gradient(135deg,#16b990,#50d1b3);color:#fff}.summary>view{display:flex;flex:1;flex-direction:column;align-items:center;border-right:1rpx solid rgba(255,255,255,.3)}.summary>view:last-child{border-right:0}.summary text{font-size:19rpx}.summary strong{margin-top:8rpx;font-size:28rpx}.notice{margin-top:16rpx;padding:16rpx;border-radius:14rpx;background:#fff8e8;color:#8b6a22;font-size:19rpx;line-height:1.6}.tabs{margin:18rpx 0;white-space:nowrap}.tabs text{display:inline-block;margin-right:10rpx;padding:11rpx 20rpx;border-radius:24rpx;background:#fff;color:#718087;font-size:20rpx}.tabs text.active{background:#10b981;color:#fff}.card{margin-bottom:14rpx;padding:20rpx;border-radius:17rpx;background:#fff}.head,.amount{display:flex;align-items:center;justify-content:space-between}.head strong{font-size:24rpx}.head text{color:#79868c;font-size:19rpx}.no{margin-top:9rpx;color:#89959a;font-size:19rpx}.amount{margin-top:14rpx}.amount text{color:#89959a;font-size:18rpx}.amount strong{color:#10b981;font-size:28rpx}.reverse{margin-top:10rpx;padding:9rpx;border-radius:8rpx;background:#fff1f0;color:#d8594c;font-size:18rpx}</style>
