<template>
  <view class="page"><jk-page-nav title="登记线下销售"/><view class="content">
    <view class="card"><view class="title">客户与成交信息</view><picker :range="customerTypes" range-key="label" @change="e=>form.customerType=customerTypes[e.detail.value].value"><view class="field"><text>客户类型</text><text>{{customerLabel}} ›</text></view></picker><view class="field"><text>客户姓名</text><input v-model.trim="form.customerName" placeholder="可选，仅加密脱敏保存"/></view><view class="field"><text>客户手机号</text><input v-model.trim="form.customerPhone" type="number" maxlength="11" placeholder="可选，仅脱敏保存"/></view><view class="field"><text>已注册用户</text><switch :checked="form.registeredCustomer" color="#16b990" @change="e=>form.registeredCustomer=e.detail.value"/></view><picker :range="payments" range-key="label" @change="e=>form.paymentMethod=payments[e.detail.value].value"><view class="field"><text>收款方式</text><text>{{paymentLabel}} ›</text></view></picker><view class="field column"><text>付款凭证地址</text><input v-model.trim="form.voucherUrl" placeholder="可选；大额无凭证将进入后台审核"/></view><view class="field column"><text>推广来源</text><input v-model.trim="form.promotionSource" placeholder="活动、地推点或推广码，可选"/></view></view>
    <view class="card"><view class="title">从本人库存选择商品</view><view v-for="(item,index) in stocks" :key="item.id||index" class="stock-row"><view class="stock-main"><text>{{item.productName||('商品'+item.productId)}}</text><text>{{item.skuName||item.skuCode||'单规格'}} · 可用 {{item.availableQty||0}}</text></view><view class="stock-actions"><input v-model.number="item.salePrice" type="digit" placeholder="售价"/><view class="qty"><text @tap="changeQty(item,-1)">−</text><strong>{{item.selectedQty||0}}</strong><text @tap="changeQty(item,1)">+</text></view></view></view><jk-empty v-if="loaded&&!stocks.length" text="暂无可销售库存"/></view>
    <view class="notice">确认后系统将真实扣减库存并读取 FIFO 批次成本。成本缺失时不会生成销售、业绩或佣金。</view>
    <button class="submit" :disabled="submitting" @tap="submit">{{submitting?'提交中…':'确认登记销售'}}</button>
  </view></view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import JkEmpty from '@/components/jk/jk-empty.vue';import{getJkMyStock}from'@/api/jk.js';import{createJkOfflineSale}from'@/api/jkV31.js';
export default{components:{JkPageNav,JkEmpty},data(){return{form:{requestNo:'OS-'+Date.now(),customerType:'NEW',customerName:'',customerPhone:'',registeredCustomer:false,paymentMethod:'WECHAT',voucherUrl:'',promotionSource:'',items:[]},stocks:[],loaded:false,submitting:false,customerTypes:[{label:'新客户',value:'NEW'},{label:'老客户',value:'EXISTING'}],payments:[{label:'微信',value:'WECHAT'},{label:'支付宝',value:'ALIPAY'},{label:'现金',value:'CASH'},{label:'银行卡',value:'BANK'}]}},computed:{customerLabel(){return(this.customerTypes.find(x=>x.value===this.form.customerType)||{}).label||'请选择'},paymentLabel(){return(this.payments.find(x=>x.value===this.form.paymentMethod)||{}).label||'请选择'}},onShow(){this.load()},methods:{value(r){return(r&&r.data)||r||[]},load(){this.loaded=false;getJkMyStock().then(r=>{const d=this.value(r);const rows=Array.isArray(d)?d:(d.list||d.items||[]);this.stocks=rows.filter(x=>Number(x.availableQty||0)>0).map(x=>Object.assign({},x,{selectedQty:0,salePrice:Number(x.retailPrice||x.price||x.referencePrice||0)}))}).finally(()=>this.loaded=true)},changeQty(i,delta){const max=Number(i.availableQty||0),next=Math.max(0,Math.min(max,Number(i.selectedQty||0)+delta));this.$set(i,'selectedQty',next)},submit(){const items=this.stocks.filter(x=>Number(x.selectedQty)>0).map(x=>({productId:x.productId,skuId:x.skuId||null,quantity:Number(x.selectedQty),unitPrice:Number(x.salePrice||0)}));if(!items.length)return uni.showToast({title:'请选择销售商品',icon:'none'});if(items.some(x=>x.unitPrice<=0))return uni.showToast({title:'请填写有效成交单价',icon:'none'});this.submitting=true;createJkOfflineSale(Object.assign({},this.form,{items})).then(r=>{const d=(r&&r.data)||r||{};uni.showToast({title:d.status==='PENDING_AUDIT'?'已提交审核':'销售已确认'});setTimeout(()=>uni.redirectTo({url:'/pages/jk/offlineSale/detail?id='+d.id}),500)}).finally(()=>this.submitting=false)}}}
</script>
<style scoped>.page{min-height:100vh;background:#f7f9f9}.content{padding:18rpx 22rpx 44rpx}.card{margin-bottom:18rpx;padding:24rpx;border-radius:20rpx;background:#fff}.title{margin-bottom:12rpx;color:#273238;font-size:28rpx;font-weight:700}.field{display:flex;align-items:center;justify-content:space-between;min-height:78rpx;border-bottom:1rpx solid #edf1f0;color:#3d4a50;font-size:23rpx}.field input{width:410rpx;text-align:right}.field.column{align-items:flex-start;flex-direction:column;padding:18rpx 0}.field.column input{width:100%;margin-top:12rpx;text-align:left}.stock-row{padding:20rpx 0;border-bottom:1rpx solid #edf1f0}.stock-main text{display:block}.stock-main text:first-child{font-size:25rpx;font-weight:700}.stock-main text:last-child{margin-top:7rpx;color:#879196;font-size:21rpx}.stock-actions{display:flex;align-items:center;justify-content:space-between;margin-top:14rpx}.stock-actions>input{width:190rpx;height:58rpx;padding:0 16rpx;border-radius:12rpx;background:#f4f7f6;font-size:22rpx}.qty{display:flex;align-items:center;gap:22rpx}.qty text{display:flex;width:48rpx;height:48rpx;align-items:center;justify-content:center;border-radius:50%;background:#e8faf5;color:#0fa981;font-size:32rpx}.qty strong{min-width:36rpx;text-align:center}.notice{margin:8rpx 4rpx 22rpx;color:#8a9498;font-size:21rpx;line-height:1.6}.submit{height:84rpx;border-radius:42rpx;background:#16b990;color:#fff;font-size:26rpx;line-height:84rpx}.submit::after{border:0}</style>
