<template>
  <view class="page"><jk-page-nav title="线下销售详情"/><view v-if="detail" class="content">
    <view class="hero"><view><text>{{detail.statusText||detail.status}}</text><small>{{statusTip}}</small></view><strong>¥{{money(detail.totalAmount)}}</strong></view>
    <view class="card"><view class="title">销售信息</view><view class="info"><text>销售单号</text><span>{{detail.saleNo}}</span></view><view class="info"><text>销售时间</text><span>{{detail.saleTime}}</span></view><view class="info"><text>客户类型</text><span>{{customerLabel(detail.customerType)}}</span></view><view class="info"><text>客户</text><span>{{detail.customerNameMasked||'--'}} {{detail.customerPhoneMasked||''}}</span></view><view class="info"><text>收款方式</text><span>{{detail.payMethod||'--'}}</span></view></view>
    <view class="card"><view class="title">商品与经营核算</view><view v-for="x in detail.items||[]" :key="x.id" class="item"><view><strong>{{x.productName||('商品 '+x.productId)}}</strong><small>{{x.skuName||x.skuCode||x.skuId}}</small></view><view><text>×{{x.quantity}}</text><strong>¥{{money(x.totalAmount)}}</strong></view><view v-if="x.costAmount!=null" class="profit"><text>实际成本 ¥{{money(x.costAmount)}}</text><text>经营毛利 ¥{{money(x.profitAmount)}}</text></view><view v-else class="profit pending">成本将在销售确认时按真实批次固化</view></view></view>
    <view class="card"><view class="title">处理记录</view><view v-for="x in detail.auditLogs||[]" :key="x.id" class="log"><view></view><view><strong>{{actionLabel(x.action)}}</strong><small>{{x.createTime}}</small><text>{{x.remark||'--'}}</text></view></view></view>
    <view class="tip">经营毛利是线下已实现收益，不进入提现账户；平台奖励是否产生，以业务发生时已发布规则为准。</view>
    <view v-if="canAction" class="actions"><button v-if="canCancel" @tap="cancel">取消销售</button><button v-if="canReturn" class="danger" @tap="returnSale">整单退货</button></view>
  </view></view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import{getJkOfflineSaleDetail,cancelJkOfflineSale,returnJkOfflineSale}from'@/api/jkV31.js';
export default{components:{JkPageNav},props:{pageId:{type:[Number,String],default:0}},data(){return{id:0,detail:null}},computed:{canCancel(){return this.detail&&['PENDING_AUDIT','PENDING_CONFIRM'].includes(this.detail.status)},canReturn(){return this.detail&&this.detail.status==='CONFIRMED'},canAction(){return this.canCancel||this.canReturn},statusTip(){const s=this.detail.status;return{PENDING_AUDIT:'等待后台核验，暂未扣减库存',CONFIRMED:'库存、业绩和经营收益已记账',REJECTED:'该销售未通过审核',RETURNED:'库存和相关收益已冲正',CANCELLED:'销售已取消'}[s]||'请以实际业务状态为准'}},created(){if(this.pageId){this.id=Number(this.pageId);this.load()}},watch:{pageId(v){if(v){this.id=Number(v);this.load()}}},onLoad(q){this.id=Number(q.id);this.load()},methods:{load(){if(!this.id)return;getJkOfflineSaleDetail(this.id).then(r=>this.detail=r.data||r||null)},money(v){const n=Number(v||0);return Number.isNaN(n)?String(v||0):n.toFixed(2)},customerLabel(v){return{REGISTERED_OLD:'老客户',REGISTERED_NEW:'新客户',ANONYMOUS:'匿名客户'}[v]||v},actionLabel(v){return{CREATE:'登记销售',CONFIRM:'确认销售',AUDIT_REJECT:'审核驳回',CANCEL:'取消销售',RETURN:'销售退货'}[v]||v},reason(title,callback){uni.showModal({title,editable:true,placeholderText:'请输入原因',success:r=>{if(r.confirm&&r.content&&r.content.trim())callback(r.content.trim());else if(r.confirm)uni.showToast({title:'原因不能为空',icon:'none'})}})},cancel(){this.reason('取消销售',reason=>cancelJkOfflineSale(this.id,{requestNo:'CANCEL-'+this.id+'-'+Date.now(),reason}).then(()=>this.load()))},returnSale(){this.reason('整单退货',reason=>returnJkOfflineSale(this.id,{requestNo:'RETURN-'+this.id+'-'+Date.now(),reason}).then(()=>{uni.showToast({title:'退货完成'});this.load()}))}}};
</script>
<style scoped>.page{min-height:100vh;background:#f7f9f9}.content{padding:16rpx 22rpx 140rpx}.hero{display:flex;align-items:center;justify-content:space-between;padding:30rpx 24rpx;border-radius:20rpx;background:linear-gradient(135deg,#14b88e,#55d2b4);color:#fff}.hero>view{display:flex;flex-direction:column;gap:8rpx}.hero text{font-size:31rpx;font-weight:700}.hero small{font-size:20rpx;opacity:.9}.hero>strong{font-size:38rpx}.card{margin-top:18rpx;padding:22rpx;border-radius:18rpx;background:#fff}.title{margin-bottom:12rpx;font-size:27rpx;font-weight:700}.info{display:flex;align-items:flex-start;justify-content:space-between;padding:14rpx 0;border-bottom:1rpx solid #edf1f0;font-size:21rpx}.info text{color:#7d898f}.info span{max-width:70%;text-align:right;color:#303b40}.item{padding:16rpx 0;border-bottom:1rpx solid #edf1f0}.item>view:first-child,.item>view:nth-child(2){display:flex;align-items:center;justify-content:space-between}.item small{color:#859197;font-size:18rpx}.item>view:nth-child(2){margin-top:8rpx}.item>view:nth-child(2) text{color:#7d898f}.item>view:nth-child(2) strong{color:#10b981}.profit{display:flex;justify-content:space-between;margin-top:10rpx;padding:10rpx;border-radius:10rpx;background:#f2fbf8;color:#187f68;font-size:19rpx}.profit.pending{color:#8b6a22;background:#fff8e8}.log{display:flex;gap:14rpx;padding:12rpx 0}.log>view:first-child{width:14rpx;height:14rpx;margin-top:8rpx;border-radius:50%;background:#10b981}.log>view:last-child{display:flex;flex:1;flex-direction:column;gap:4rpx}.log small{color:#959fa4;font-size:17rpx}.log text{color:#5f6c72;font-size:20rpx}.tip{margin-top:18rpx;padding:16rpx;color:#7d898f;font-size:19rpx;line-height:1.6}.actions{position:fixed;right:0;bottom:0;left:0;display:flex;gap:18rpx;padding:18rpx 22rpx calc(18rpx + env(safe-area-inset-bottom));background:#fff}.actions button{flex:1;height:78rpx;border:1rpx solid #dce5e3;border-radius:39rpx;background:#fff;color:#59666c;font-size:25rpx;line-height:78rpx}.actions button.danger{border:0;background:#ef5b4c;color:#fff}</style>
