<template>
  <view class="page"><jk-page-nav title="线下销售记录"/><view class="content">
    <view class="top"><view><text>真实库存销售记录</text><small>经营收益与平台佣金分开核算</small></view><button @tap="goCreate">登记销售</button></view>
    <scroll-view scroll-x class="tabs"><text v-for="x in tabs" :key="x.value" :class="{active:status===x.value}" @tap="changeStatus(x.value)">{{x.label}}</text></scroll-view>
    <view v-for="x in list" :key="x.id" class="card" @tap="open(x)"><view class="head"><strong>{{x.saleNo}}</strong><jk-status-tag :text="x.statusText||x.status" :tone="tone(x.status)"/></view><view class="row"><text>{{customerLabel(x.customerType)}}</text><text>{{x.saleTime||x.createTime}}</text></view><view class="amount"><text>共 {{x.totalQuantity||0}} 件</text><strong>¥{{money(x.totalAmount)}}</strong></view><view v-if="x.auditRequired" class="risk">该销售触发审核条件</view></view>
    <jk-empty v-if="loaded&&!list.length" text="暂无线下销售记录"/>
    <view v-if="hasMore" class="more" @tap="loadMore">加载更多</view>
  </view></view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import JkStatusTag from '@/components/jk/jk-status-tag.vue';import JkEmpty from '@/components/jk/jk-empty.vue';import{getJkOfflineSaleList}from'@/api/jkV31.js';
export default{components:{JkPageNav,JkStatusTag,JkEmpty},data(){return{status:'',page:1,limit:20,total:0,list:[],loaded:false,tabs:[{label:'全部',value:''},{label:'待审核',value:'PENDING_AUDIT'},{label:'已确认',value:'CONFIRMED'},{label:'已退货',value:'RETURNED'},{label:'已驳回',value:'REJECTED'}]}},computed:{hasMore(){return this.list.length<this.total}},created(){this.load(true)},onShow(){this.page=1;this.load(true)},methods:{load(reset){this.loaded=false;getJkOfflineSaleList({page:this.page,limit:this.limit,status:this.status||undefined}).then(r=>{const d=r.data||r||{};const rows=d.list||d.records||(Array.isArray(d)?d:[]);this.total=Number(d.total||rows.length);this.list=reset?rows:this.list.concat(rows)}).finally(()=>this.loaded=true)},changeStatus(v){this.status=v;this.page=1;this.load(true)},loadMore(){this.page++;this.load(false)},goCreate(){uni.navigateTo({url:'/pages/jk/trade/list?mode=offlineSaleCreate'})},open(x){uni.navigateTo({url:'/pages/jk/trade/list?mode=offlineSaleDetail&id='+x.id})},money(v){const n=Number(v||0);return Number.isNaN(n)?String(v||0):n.toFixed(2)},customerLabel(v){return{REGISTERED_OLD:'老客户',REGISTERED_NEW:'新客户',ANONYMOUS:'匿名客户'}[v]||v},tone(v){if(v==='CONFIRMED')return'success';if(v==='REJECTED')return'danger';if(v==='PENDING_AUDIT')return'warning';return'neutral'}}};
</script>
<style scoped>.page{min-height:100vh;background:#f7f9f9}.content{padding:16rpx 22rpx 38rpx}.top{display:flex;align-items:center;justify-content:space-between;padding:22rpx;border-radius:20rpx;background:linear-gradient(135deg,#eafbf6,#fff)}.top>view{display:flex;flex-direction:column;gap:7rpx}.top text{font-size:27rpx;font-weight:700}.top small{color:#7d898f;font-size:19rpx}.top button{height:58rpx;margin:0;padding:0 18rpx;border-radius:29rpx;background:#10b981;color:#fff;font-size:21rpx;line-height:58rpx}.tabs{margin:18rpx 0;white-space:nowrap}.tabs text{display:inline-block;margin-right:12rpx;padding:12rpx 22rpx;border-radius:28rpx;background:#fff;color:#728087;font-size:21rpx}.tabs text.active{background:#10b981;color:#fff}.card{margin-bottom:16rpx;padding:22rpx;border-radius:18rpx;background:#fff}.head,.row,.amount{display:flex;align-items:center;justify-content:space-between}.head strong{font-size:24rpx}.row{margin-top:14rpx;color:#7d898f;font-size:20rpx}.amount{margin-top:16rpx;padding-top:14rpx;border-top:1rpx solid #edf1f0}.amount text{color:#7d898f;font-size:20rpx}.amount strong{color:#10b981;font-size:29rpx}.risk{margin-top:12rpx;padding:10rpx;border-radius:10rpx;background:#fff7e6;color:#a36c0d;font-size:19rpx}.more{text-align:center;padding:22rpx;color:#10a981;font-size:22rpx}</style>
