<template>
  <view class="page"><jk-page-nav title="健康报告"/><view class="content">
    <view class="notice">报告只整理本人真实健康记录，不生成诊断、处方或虚构设备数据。</view>
    <view class="generate"><view class="type"><text :class="{active:form.reportType==='WEEKLY'}" @tap="form.reportType='WEEKLY'">周报</text><text :class="{active:form.reportType==='MONTHLY'}" @tap="form.reportType='MONTHLY'">月报</text></view><view class="dates"><picker mode="date" :value="form.periodStart" @change="form.periodStart=$event.detail.value"><text>{{form.periodStart||'开始日期'}}</text></picker><span>至</span><picker mode="date" :value="form.periodEnd" @change="form.periodEnd=$event.detail.value"><text>{{form.periodEnd||'结束日期'}}</text></picker></view><button :disabled="generating" @tap="generate">{{generating?'生成中...':'基于真实记录生成报告'}}</button></view>
    <view v-for="x in list" :key="x.id" class="card" @tap="open(x)"><view class="head"><strong>{{x.reportType==='WEEKLY'?'健康周报':'健康月报'}}</strong><text>{{date(x.periodStart)}} - {{date(x.periodEnd)}}</text></view><view class="metrics"><view><text>记录</text><strong>{{x.recordCount||0}}</strong></view><view><text>平均血糖</text><strong>{{x.averageGlucose==null?'--':x.averageGlucose}}</strong></view><view><text>高/低风险</text><strong>{{x.highCount||0}}/{{x.lowCount||0}}</strong></view></view><small>{{x.summaryText||'点击查看报告详情'}}</small></view>
    <jk-empty v-if="loaded&&!list.length" text="暂无健康报告"/>
  </view>
  <view v-if="detail" class="mask" @tap="detail=null"><view class="sheet" @tap.stop><view class="sheet-head"><strong>{{detail.reportType==='WEEKLY'?'健康周报':'健康月报'}}</strong><text @tap="detail=null">关闭</text></view><view class="summary">{{detail.summaryText||'该周期暂无可汇总记录。'}}</view><view class="grid"><view><text>血糖记录</text><strong>{{detail.glucoseCount||0}}</strong></view><view><text>平均值</text><strong>{{detail.averageGlucose||'--'}}</strong></view><view><text>最低/最高</text><strong>{{detail.minimumGlucose||'--'}}/{{detail.maximumGlucose||'--'}}</strong></view><view><text>饮食/运动/用药</text><strong>{{detail.dietCount||0}}/{{detail.exerciseCount||0}}/{{detail.medicineCount||0}}</strong></view></view><view class="medical">本报告仅用于健康记录整理，不构成医疗诊断。</view></view></view>
  </view>
</template>
<script>
import JkPageNav from '@/components/jk/jk-page-nav.vue';import JkEmpty from '@/components/jk/jk-empty.vue';import{generateJkHealthReport,getJkHealthReportList,getJkHealthReportDetail}from'@/api/jkV31.js';
function format(d){return d.toISOString().slice(0,10)}
export default{components:{JkPageNav,JkEmpty},data(){const end=new Date(),start=new Date();start.setDate(end.getDate()-6);return{form:{reportType:'WEEKLY',periodStart:format(start),periodEnd:format(end)},list:[],loaded:false,generating:false,detail:null}},onShow(){this.load()},methods:{load(){this.loaded=false;getJkHealthReportList({page:1,limit:100}).then(r=>{const d=r.data||r||[];this.list=Array.isArray(d)?d:(d.list||d.records||[])}).finally(()=>this.loaded=true)},generate(){if(!this.form.periodStart||!this.form.periodEnd)return this.$util.Tips({title:'请选择报告周期'});this.generating=true;generateJkHealthReport({...this.form,requestNo:'HEALTH-REPORT-'+Date.now()}).then(()=>{this.$util.Tips({title:'报告已生成'});this.load()}).finally(()=>this.generating=false)},open(x){getJkHealthReportDetail(x.id).then(r=>this.detail=r.data||r||null)},date(v){return v?String(v).slice(0,10):'--'}}};
</script>
<style scoped>.page{min-height:100vh;background:#f7f9f9}.content{padding:16rpx 22rpx 40rpx}.notice{padding:17rpx;border-radius:14rpx;background:#eef8f5;color:#58736b;font-size:20rpx;line-height:1.6}.generate{margin-top:16rpx;padding:20rpx;border-radius:19rpx;background:#fff}.type{display:flex;gap:12rpx}.type text{flex:1;padding:14rpx;border-radius:12rpx;background:#f3f7f6;color:#78858b;text-align:center;font-size:22rpx}.type text.active{background:#e9faf5;color:#10a981;font-weight:700}.dates{display:flex;align-items:center;justify-content:space-between;margin-top:16rpx}.dates picker{flex:1;padding:15rpx;border-radius:12rpx;background:#f6f8f8;text-align:center;font-size:21rpx}.dates span{margin:0 10rpx;color:#879299}.generate button{height:72rpx;margin-top:16rpx;border-radius:36rpx;background:#10b981;color:#fff;font-size:23rpx;line-height:72rpx}.card{margin-top:15rpx;padding:20rpx;border-radius:18rpx;background:#fff}.head{display:flex;align-items:center;justify-content:space-between}.head strong{font-size:25rpx}.head text{color:#89959a;font-size:18rpx}.metrics{display:flex;margin-top:16rpx}.metrics view{display:flex;flex:1;flex-direction:column;align-items:center;border-right:1rpx solid #edf1f0}.metrics view:last-child{border-right:0}.metrics text{color:#879299;font-size:18rpx}.metrics strong{margin-top:6rpx;color:#10a981;font-size:25rpx}.card>small{display:block;margin-top:15rpx;overflow:hidden;color:#6f7c82;font-size:19rpx;text-overflow:ellipsis;white-space:nowrap}.mask{position:fixed;z-index:100;inset:0;background:rgba(0,0,0,.43)}.sheet{position:absolute;right:0;bottom:0;left:0;padding:25rpx 23rpx calc(26rpx + env(safe-area-inset-bottom));border-radius:28rpx 28rpx 0 0;background:#fff}.sheet-head{display:flex;justify-content:space-between}.sheet-head strong{font-size:29rpx}.sheet-head text{color:#7d898f;font-size:22rpx}.summary{margin-top:18rpx;padding:17rpx;border-radius:14rpx;background:#f3faf8;color:#526761;font-size:21rpx;line-height:1.7}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12rpx;margin-top:17rpx}.grid view{display:flex;flex-direction:column;gap:7rpx;padding:16rpx;border-radius:13rpx;background:#f7f9f9}.grid text{color:#879299;font-size:18rpx}.grid strong{font-size:23rpx}.medical{margin-top:17rpx;color:#9a6b1b;font-size:18rpx;text-align:center}</style>