<template>
  <view class="material-page"><jk-page-nav title="推广素材"/><view class="tabs"><text v-for="item in tabs" :key="item.value" :class="{active:active===item.value}" @tap="active=item.value">{{item.label}}</text></view><view class="material-content"><view v-for="(item,index) in filteredMaterials" :key="item.id" class="material-card"><image :src="item.image" mode="aspectFill" @tap="preview(item.image)"/><view class="card-body"><text>{{item.title}}</text><small>{{item.desc}}</small><view><button @tap="copyText(item)">复制文案</button><button @tap="preview(item.image)">预览素材</button></view></view></view><jk-empty v-if="!filteredMaterials.length" text="暂无推广素材"/><button class="save-btn" @tap="saveSelected">保存到相册</button><view class="api-tip"><jk-icon name="info" size="sm"/><text>当前项目没有推广素材列表接口，本页使用 image2 生成的本地素材；接入接口后可替换为后台素材。</text></view></view></view>
</template>
<script>
import JkPageNav from'@/components/jk/jk-page-nav.vue';import JkIcon from'@/components/jk/jk-icon.vue';import JkEmpty from'@/components/jk/jk-empty.vue';export default{components:{JkPageNav,JkIcon,JkEmpty},data(){return{active:'poster',selected:0,tabs:[{label:'文案素材',value:'copy'},{label:'商品素材',value:'product'},{label:'健康知识',value:'health'},{label:'海报素材',value:'poster'}],materials:[{id:1,type:'poster',title:'邀请您加入九州康',desc:'共享健康事业新机遇',image:'/static/jk-ui-v2/banners/promotion-banner.png',copy:'邀请您加入九州康，共享健康事业新机遇。'},{id:2,type:'health',title:'做健康事业，知识与服务并重',desc:'适用于健康知识推广',image:'/static/jk-ui-v2/banners/identity-banner.png',copy:'关注健康、管理健康、分享健康。'},{id:3,type:'product',title:'健康产品，品质生活',desc:'适用于商品与服务推广',image:'/static/jk-ui-v2/banners/gift-banner.png',copy:'精选健康产品，为家人提供更安心的日常守护。'},{id:4,type:'copy',title:'轻创业，高收益',desc:'适用于朋友圈业务邀请',image:'/static/jk-ui-v2/banners/finance-banner.png',copy:'轻量开启健康事业，积累长期服务价值。'}]}},computed:{filteredMaterials(){return this.materials.filter(x=>x.type===this.active)}},methods:{preview(url){uni.previewImage({urls:[url],current:url})},copyText(item){uni.setClipboardData({data:item.copy||item.title})},saveSelected(){const item=this.filteredMaterials[0];if(!item)return;uni.showToast({title:'本地包内素材需发布后使用下载地址保存',icon:'none'})}}};
</script>
<style scoped>
.material-page{min-height:100vh;background:#f7f9f9}.tabs{display:flex;border-bottom:1rpx solid #edf1f0;background:#fff}.tabs text{position:relative;flex:1;padding:20rpx 0;color:#707c82;text-align:center;font-size:22rpx}.tabs text.active{color:#10b981;font-weight:700}.tabs text.active::after{position:absolute;right:30%;bottom:0;left:30%;height:4rpx;background:#10b981;content:''}.material-content{padding:18rpx 22rpx 36rpx}.material-card{margin-bottom:18rpx;overflow:hidden;border-radius:18rpx;background:#fff;box-shadow:0 7rpx 20rpx rgba(24,68,58,.04)}.material-card>image{width:100%;height:360rpx}.card-body{padding:18rpx}.card-body>text{display:block;color:#273239;font-size:26rpx;font-weight:700}.card-body>small{display:block;margin-top:7rpx;color:#869197;font-size:20rpx}.card-body>view{display:flex;gap:12rpx;margin-top:16rpx}.card-body button{flex:1;height:62rpx;margin:0;border-radius:31rpx;background:#eefaf7;color:#10a981;font-size:21rpx;line-height:62rpx}.card-body button::after{border:0}.save-btn{height:76rpx;border:2rpx solid #10b981;border-radius:38rpx;background:#fff;color:#10a981;font-size:25rpx;line-height:76rpx}.api-tip{display:flex;align-items:flex-start;gap:8rpx;margin-top:16rpx;padding:16rpx;border-radius:14rpx;background:#fff7e8;color:#8d6928;font-size:19rpx;line-height:1.55}
</style>
