<template>
  <view class="page"><jk-page-nav title="我的推广码"/><view class="content">
    <view class="poster"><view class="brand"><image src="/static/jk-ui-v2/icons/identity.png"/><view><strong>九州康业</strong><text>健康事业伙伴推广</text></view></view><view class="copy"><text>邀请您加入</text><strong>共享健康事业新机遇</strong></view><view class="qr-wrap"><image v-if="localQrPath" :src="localQrPath" mode="aspectFit"/><view v-else class="placeholder"><jk-icon name="qrcode" size="xl"/><text>{{loading?'正在生成真实微信小程序码':errorMessage||'推广码暂不可用'}}</text></view><view class="scan"><strong>微信扫码进入小程序</strong><text>首次有效关系默认保持，换绑必须提交审核</text></view></view><view class="safe">该图片来自微信官方小程序码接口，不使用前端模拟二维码或占位图。</view></view>
    <view v-if="errorMessage" class="warning">{{errorMessage}}。请由管理员检查微信总开关、appid/secret、私有文件存储和推广场景启用状态。</view>
    <view class="actions"><button :disabled="!localQrPath" @tap="save"><jk-icon name="withdraw" size="sm"/>保存小程序码</button><button :disabled="!data.pagePath" @tap="copy"><jk-icon name="qrcode" size="sm"/>复制页面路径</button><button @tap="reload"><jk-icon name="flow" size="sm"/>重新生成</button></view>
    <view class="info"><view><text>场景</text><strong>{{data.sceneName||'代理关系绑定'}}</strong></view><view><text>scene</text><strong>{{data.sceneValue||'--'}}</strong></view><view><text>生成状态</text><strong>{{statusText}}</strong></view></view>
  </view></view>
</template>
<script>
import JkPageNav from'@/components/jk/jk-page-nav.vue';import JkIcon from'@/components/jk/jk-icon.vue';import{generateJkPromotionCode}from'@/api/jkV31.js';import{HTTP_REQUEST_URL,HEADER,TOKENNAME}from'@/config/app';import store from'@/store';
export default{components:{JkPageNav,JkIcon},data(){return{data:{},localQrPath:'',loading:false,errorMessage:''}},computed:{statusText(){return{SUCCESS:'已生成',FAILED:'生成失败',GENERATING:'生成中'}[this.data.status]||this.data.status||'未生成'}},onShow(){this.reload()},methods:{reload(){this.loading=true;this.errorMessage='';this.localQrPath='';generateJkPromotionCode('AGENT_BIND','PROMOTION-'+Date.now()).then(r=>{this.data=r.data||r||{};if(this.data.status==='SUCCESS'&&this.data.downloadPath)this.download(this.data.downloadPath);else this.errorMessage=this.data.errorMessage||'微信未返回可用小程序码'}).catch(e=>{this.errorMessage=String(e&&e.message||e||'推广码生成失败')}).finally(()=>this.loading=false)},download(path){const header=Object.assign({},HEADER);if(store.state.app.token)header[TOKENNAME]=store.state.app.token;uni.downloadFile({url:HTTP_REQUEST_URL+path,header,success:r=>{if(r.statusCode===200)this.localQrPath=r.tempFilePath;else this.errorMessage='私有推广码下载失败'},fail:()=>{this.errorMessage='私有推广码下载失败'}})},save(){if(!this.localQrPath)return;uni.saveImageToPhotosAlbum({filePath:this.localQrPath,success:()=>uni.showToast({title:'已保存到相册'}),fail:()=>uni.showToast({title:'保存失败，请检查相册权限',icon:'none'})})},copy(){if(!this.data.pagePath)return;uni.setClipboardData({data:this.data.pagePath})}}};
</script>
<style scoped>.page{min-height:100vh;background:#f7f9f9}.content{padding:16rpx 22rpx 40rpx}.poster{overflow:hidden;padding:24rpx;border-radius:22rpx;background:linear-gradient(145deg,#d9faf1,#fff);box-shadow:0 8rpx 24rpx rgba(24,70,59,.06)}.brand{display:flex;align-items:center}.brand image{width:58rpx;height:58rpx}.brand>view{display:flex;flex-direction:column;gap:4rpx;margin-left:10rpx}.brand strong{color:#0e9d7f;font-size:27rpx}.brand text{color:#758680;font-size:18rpx}.copy{display:flex;flex-direction:column;margin-top:24rpx}.copy text{color:#10b981;font-size:38rpx;font-weight:800}.copy strong{margin-top:6rpx;color:#213038;font-size:29rpx}.qr-wrap{display:flex;align-items:center;margin-top:26rpx;padding:22rpx;border-radius:18rpx;background:rgba(255,255,255,.94)}.qr-wrap>image,.placeholder{width:260rpx;height:260rpx;flex-shrink:0}.placeholder{display:flex;flex-direction:column;align-items:center;justify-content:center;border:1rpx dashed #bcded5;color:#738780;text-align:center;font-size:19rpx}.placeholder text{margin-top:10rpx}.scan{display:flex;flex-direction:column;gap:12rpx;margin-left:24rpx}.scan strong{color:#10a981;font-size:25rpx}.scan text{color:#71817d;font-size:19rpx;line-height:1.6}.safe{margin-top:18rpx;color:#72827e;font-size:18rpx;text-align:center}.warning{margin-top:16rpx;padding:17rpx;border-radius:14rpx;background:#fff6e6;color:#956818;font-size:20rpx;line-height:1.6}.actions{display:flex;gap:10rpx;margin-top:16rpx}.actions button{display:flex;flex:1;align-items:center;justify-content:center;height:68rpx;margin:0;border-radius:15rpx;background:#fff;color:#344249;font-size:19rpx;line-height:68rpx}.actions button[disabled]{opacity:.45}.actions button::after{border:0}.info{margin-top:16rpx;padding:20rpx;border-radius:18rpx;background:#fff}.info>view{display:flex;align-items:center;justify-content:space-between;min-height:62rpx;border-bottom:1rpx solid #edf1f0}.info>view:last-child{border-bottom:0}.info text{color:#7d898f;font-size:20rpx}.info strong{max-width:68%;overflow:hidden;color:#29363c;font-size:21rpx;text-overflow:ellipsis;white-space:nowrap}</style>