<template>
  <view class="identity-detail"><jk-page-nav title="申请详情"></jk-page-nav>
    <view v-if="application.id" class="content"><view class="timeline"><view v-for="(step,index) in steps" :key="index" class="step"><view :class="['dot', { done: step.done, result: index === 3 && step.done }]">{{ step.done ? '✓' : index + 1 }}</view><view class="step-title">{{ step.title }}</view><text>{{ step.time ? formatTime(step.time) : '待审核' }}</text></view></view>
      <view class="card"><view class="card-title">申请信息</view><view class="info-row"><text>申请身份</text><strong>{{ application.applyRoleName }}</strong></view><view class="info-row"><text>申请人</text><strong>{{ application.applicantName || application.userNickname || '-' }}</strong></view><view class="info-row"><text>手机号码</text><strong>{{ application.applicantPhone || '-' }}</strong></view><view class="info-row"><text>所属区域</text><strong>{{ application.regionName || application.regionCode || '-' }}</strong></view><view class="info-row"><text>推荐人</text><strong>{{ recommenderText || '-' }}</strong></view><view class="info-row reason-row"><text>申请说明</text><strong>{{ reasonText || '-' }}</strong></view></view>
      <view v-if="files.length" class="card"><view class="card-title">申请资料</view><view class="file-list"><image v-for="url in files" :key="url" :src="url" mode="aspectFill" @click="preview(url)"></image></view></view>
      <view v-if="application.auditStatus === 'REJECTED'" class="reject-card"><text>拒绝原因</text><strong>{{ application.rejectReason || '审核未通过，请联系平台客服了解详情。' }}</strong></view>
      <button v-if="isFinished" class="result-btn" @click="goResult">查看审核结果</button>
    </view>
  </view>
</template>
<script>
import { getJkIdentityApplyDetail, getJkIdentityApplyList } from '@/api/jk.js'; import JkPageNav from '@/components/jk/jk-page-nav.vue';
export default { components:{JkPageNav}, data(){return{application:{},auditLogs:[]};}, computed:{ files(){try{const rows=JSON.parse(this.application.certificateFiles||'[]');return Array.isArray(rows)?rows:[];}catch(e){return (this.application.certificateFiles||'').split(',').filter(Boolean);} }, recommenderText(){const match=(this.application.applyReason||'').match(/(?:^|\n)推荐人：([^\n]*)$/);return match?match[1].trim():'';}, reasonText(){return (this.application.applyReason||'').replace(/(?:^|\n)推荐人：[^\n]*$/,'').trim();}, isFinished(){return ['EFFECTIVE','APPROVED','REJECTED','FROZEN'].indexOf(this.application.auditStatus)>=0;}, steps(){const logs=this.auditLogs||[];const reviewOne=logs.length>1?logs[0]:null;const reviewTwo=logs.length>2?logs[1]:null;const resultLog=this.isFinished&&logs.length?logs[logs.length-1]:null;return [{title:'提交申请',time:this.application.createTime,done:!!this.application.createTime},{title:'区县代初审',time:reviewOne?reviewOne.createTime:'',done:!!reviewOne},{title:'平台复审',time:reviewTwo?reviewTwo.createTime:'',done:!!reviewTwo},{title:'审核结果',time:resultLog?resultLog.createTime:'',done:!!resultLog}];} }, onLoad(q){this.id=q.id;this.loadDetail();}, methods:{loadDetail(){getJkIdentityApplyDetail(this.id).then(res=>{const data=res.data||res||{};this.application=data.application||{};this.auditLogs=data.auditLogs||[];}).catch(()=>this.loadFromList());},loadFromList(){getJkIdentityApplyList({page:1,limit:50}).then(res=>{const data=res.data||res||{};const rows=Array.isArray(data)?data:(data.list||data.records||[]);this.application=rows.filter(item=>String(item.id)===String(this.id))[0]||{};if(!this.application.id)this.$util.Tips({title:'申请记录不存在'});}).catch(err=>this.$util.Tips({title:err||'详情加载失败'}));},formatTime(v){return v?String(v).replace('T',' ').slice(0,16):'待审核';},preview(url){uni.previewImage({current:url,urls:this.files});},goResult(){uni.navigateTo({url:'/pages/jk/identity/result?id='+this.application.id});}} };
</script>
<style lang="scss">
.identity-detail{min-height:100vh;padding:0 30rpx 60rpx;background:#f7faf9;box-sizing:border-box}.timeline,.card,.reject-card{margin-top:26rpx;padding:30rpx;border-radius:22rpx;background:#fff;box-shadow:0 8rpx 28rpx rgba(40,75,66,.06)}.timeline{display:flex;justify-content:space-between}.step{position:relative;flex:1;min-width:0;text-align:center}.step:not(:last-child):after{position:absolute;top:26rpx;left:62%;width:76%;height:4rpx;background:#dcebe7;content:''}.dot{position:relative;z-index:1;width:52rpx;height:52rpx;margin:0 auto 16rpx;border:4rpx solid #cbd5d4;border-radius:50%;background:#fff;color:#98a4a3;line-height:52rpx;font-size:26rpx}.dot.done{border-color:#08b996;color:#08b996}.dot.result{border-width:8rpx;background:#08b996;color:#fff;box-shadow:0 0 0 10rpx #def8f1}.step-title{color:#27303c;font-size:25rpx;white-space:nowrap}.step text{display:block;margin-top:10rpx;color:#87909d;font-size:20rpx;white-space:nowrap}.card-title{margin-bottom:18rpx;color:#202633;font-size:35rpx;font-weight:700}.info-row{display:flex;justify-content:space-between;gap:24rpx;min-height:82rpx;border-bottom:1rpx solid #edf0f2;align-items:center}.info-row:last-child{border:0}.info-row text{color:#7e8795;font-size:28rpx}.info-row strong{max-width:460rpx;color:#27303c;text-align:right;font-size:28rpx;font-weight:500}.reason-row{align-items:flex-start;padding:22rpx 0}.reason-row strong{line-height:1.6}.file-list{display:flex;gap:18rpx}.file-list image{width:180rpx;height:180rpx;border-radius:12rpx}.reject-card{display:flex;flex-direction:column;gap:15rpx;background:#fff6f4;color:#ff5a4c}.reject-card text{font-size:30rpx;font-weight:700}.reject-card strong{color:#4b3940;font-size:27rpx;font-weight:400;line-height:1.7}.result-btn{height:92rpx;margin-top:40rpx;border-radius:46rpx;background:#08b996;color:#fff;line-height:92rpx;font-size:33rpx}
</style>
