<template>
  <view class="identity-status"><jk-page-nav title="身份状态"></jk-page-nav>
    <view class="status-hero"><view class="avatar">{{ roleName.slice(0,1) }}</view><view class="hero-main"><view><strong>{{ roleName }}</strong><text :class="{ frozen: context.freezeStatus }">{{ context.freezeStatus ? '身份冻结' : '身份正常' }}</text></view><view>{{ context.regionName || context.regionCode || '暂未绑定区域' }}</view><view>有效期：长期有效</view></view><view class="hero-mark">✓</view></view>
    <view class="card"><view class="card-title">身份信息</view><view class="info-row"><text>身份类型</text><strong>{{ roleName }}</strong></view><view class="info-row"><text>所属区域</text><strong>{{ context.regionName || context.regionCode || '-' }}</strong></view><view class="info-row"><text>有效期</text><strong>长期有效</strong></view><view class="info-row"><text>开通时间</text><strong>{{ formatTime(context.effectiveTime) }}</strong></view><view class="info-row"><text>审核状态</text><strong>{{ context.auditStatusText || context.identityStatusText || statusText }}</strong></view></view>
    <view class="card"><view class="card-title">权限能力</view><view v-if="permissionItems.length"><view v-for="item in permissionItems" :key="item.code" class="permission-row"><text class="check">✓</text><strong>{{ item.name }}</strong><text class="arrow">›</text></view></view><view v-else class="empty">当前身份暂无业务权限</view></view>
    <view class="card"><view class="card-title">业务入口</view><view class="business-grid"><view @click="goBusinessCenter"><text>▦</text><strong>进入业务中台</strong></view></view></view>
    <view class="tip">如身份信息有误，请联系平台客服</view><button v-if="context.canApplyRoles && context.canApplyRoles.length" class="apply-btn" @click="goApply">申请新的业务身份</button><button class="records-btn" @click="goList">查看申请记录</button>
  </view>
</template>
<script>
import { getJkPermissionContext } from '@/api/jk.js'; import JkPageNav from '@/components/jk/jk-page-nav.vue'; import { jkAuditStatusText } from '@/utils/jk-display.js';
const ROLE={normal_user:'普通用户',maker:'创客',partner:'合伙人',county_agent:'区县代',health_advisor:'健康顾问',city_agent:'市级代理',province_agent:'省级代理'};
const PERMISSIONS={ 'stock.platform.order':'平台订货','stock.transfer.audit':'调拨审核','stock.view.self':'库存管理','commission.view.self':'收益查看','team.view':'团队管理','product.trade.view':'商品业务查看' };
export default {components:{JkPageNav},data(){return {context:{permissions:[],canApplyRoles:[]}};},computed:{roleName(){return this.context.primaryRoleName||ROLE[this.context.primaryRoleCode]||'普通用户';},statusText(){return jkAuditStatusText(this.context.auditStatus);},permissionItems(){return (this.context.permissions||[]).filter(code=>PERMISSIONS[code]).map(code=>({code,name:PERMISSIONS[code]}));}},onShow(){this.load();},methods:{load(){getJkPermissionContext().then(res=>{this.context=Object.assign({permissions:[],canApplyRoles:[]},res.data||res||{});}).catch(err=>this.$util.Tips({title:err||'身份状态加载失败'}));},formatTime(v){return v?String(v).replace('T',' ').slice(0,16):'-';},goBusinessCenter(){if(this.context.freezeStatus)return this.$util.Tips({title:'当前身份已冻结'});uni.navigateTo({url:'/pages/jk/business/index'});},goApply(){uni.navigateTo({url:'/pages/jk/identity/select'});},goList(){uni.navigateTo({url:'/pages/jk/identity/applyList'});}}};
</script>
<style lang="scss">
.identity-status{min-height:100vh;padding:0 26rpx 80rpx;background:#f8fbfa;box-sizing:border-box}.status-hero{display:flex;align-items:center;min-height:194rpx;margin:28rpx 0;padding:28rpx;border:1rpx solid #c8eee5;border-radius:24rpx;background:linear-gradient(135deg,#e9fbf6,#f9fffd)}.avatar{display:flex;align-items:center;justify-content:center;width:112rpx;height:112rpx;margin-right:25rpx;border-radius:50%;background:#0bc49f;color:#fff;font-size:50rpx;font-weight:700}.hero-main{display:flex;flex:1;flex-direction:column;gap:12rpx;color:#657181;font-size:27rpx}.hero-main>view:first-child{display:flex;align-items:center;gap:16rpx}.hero-main strong{color:#202633;font-size:39rpx}.hero-main text{padding:8rpx 16rpx;border-radius:12rpx;background:#09ba96;color:#fff;font-size:23rpx;white-space:nowrap}.hero-main .frozen{background:#ff786b}.hero-mark{color:#a6ecdd;font-size:100rpx}.card{margin-bottom:24rpx;padding:0 28rpx;border-radius:24rpx;background:#fff;box-shadow:0 6rpx 22rpx rgba(40,70,62,.05)}.card-title{padding:30rpx 0 18rpx;color:#202633;font-size:36rpx;font-weight:700}.info-row,.permission-row{display:flex;align-items:center;min-height:82rpx;border-bottom:1rpx solid #edf0f2}.info-row:last-child,.permission-row:last-child{border:0}.info-row text{color:#727d8c;font-size:28rpx}.info-row strong{margin-left:auto;color:#27303c;font-size:28rpx;font-weight:500}.permission-row .check{display:flex;align-items:center;justify-content:center;width:34rpx;height:34rpx;margin-right:22rpx;border-radius:50%;background:#08bd99;color:#fff;font-size:22rpx}.permission-row strong{color:#3d4653;font-size:28rpx;font-weight:500}.permission-row .arrow{margin-left:auto;color:#9ba4b0;font-size:42rpx}.business-grid{display:flex;justify-content:space-around;padding:14rpx 0 34rpx}.business-grid view{display:flex;flex-direction:column;align-items:center;gap:12rpx}.business-grid text{display:flex;align-items:center;justify-content:center;width:80rpx;height:80rpx;border-radius:18rpx;background:#e0faf3;color:#09b892;font-size:42rpx}.business-grid strong{color:#4b5664;font-size:25rpx;font-weight:500}.empty{padding:30rpx 0;color:#919aa6;text-align:center;font-size:26rpx}.tip{margin:20rpx 8rpx;color:#5c9f90;font-size:25rpx}.apply-btn,.records-btn{height:92rpx;margin-top:20rpx;border-radius:46rpx;line-height:92rpx;font-size:31rpx}.apply-btn{background:#08b996;color:#fff}.records-btn{border:2rpx solid #08b996;background:#fff;color:#08b996}
</style>
